kind: Service
apiVersion: v1
metadata:
  #Service name
  name: nodejs-app-svc
spec:
  selector:
    app: dogwood-channel-173007
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer