kind: Service
apiVersion: v1
metadata:
  #Service name
  name: nginx-app-svc
spec:
  selector:
    app: dogwood-channel-173007
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
  type: LoadBalancer